FROM node:18-alpine

## ENV VARS
## CORE
ARG VITE_ENVIRONMENT
ENV VITE_ENVIRONMENT=${VITE_ENVIRONMENT}
ARG VITE_MAINTENANCE
ENV VITE_MAINTENANCE=${VITE_MAINTENANCE}
## APPWRITE DEV
ARG VITE_APPWRITE_ENDPOINT
ENV VITE_APPWRITE_ENDPOINT=${VITE_APPWRITE_ENDPOINT}
ARG VITE_APPWRITE_PROJECT_ID
ENV VITE_APPWRITE_PROJECT_ID=${VITE_APPWRITE_PROJECT_ID}
## APPWRITE PROD
ARG VITE_APPWRITE_ENDPOINT_PROD
ENV VITE_APPWRITE_ENDPOINT_PROD=${VITE_APPWRITE_ENDPOINT_PROD}
ARG VITE_APPWRITE_PROJECT_ID_PROD
ENV VITE_APPWRITE_PROJECT_ID_PROD=${VITE_APPWRITE_PROJECT_ID_PROD}
### STRIPE
ARG VITE_STRIPE_SECRET_KEY
ENV VITE_STRIPE_SECRET_KEY=${VITE_STRIPE_SECRET_KEY}
ARG VITE_STRIPE_PUBLIC_KEY
ENV VITE_STRIPE_PUBLIC_KEY=${VITE_STRIPE_PUBLIC_KEY}

WORKDIR /app

COPY package.json  ./

RUN npm install -g pnpm vite

COPY . .

RUN pnpm install
RUN pnpm build

FROM node:18-alpine

WORKDIR /app

COPY --from=0 /app/package*.json ./

#RUN pnpm install --production --ignore-scripts
#RUN pnpm audit fix

COPY --from=0 /app ./

EXPOSE 3000

CMD ["node", "build"]